<a href="https://colab.research.google.com/github/buunq1977/CodexploreRepo/blob/main/M3.1.1d_%5BLab_solution%5D_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://i.imgur.com/0AUxkXt.png)

# Numpy Lab

![alt text](https://i.morioh.com/b53d97587a.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays.

In [ ]:
import numpy as np

For each of this exercise, try different method to produce the output

## Describe a Matrix

In [ ]:
a = np.array([np.ones(5), np.ones(5)])
b = np.array([np.zeros(5), np.zeros(5)])
c = np.array([np.zeros(5), np.zeros(5)])

r = np.array([a, b, c])
r

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

**Try to answer the question by yourself first, and double-check by code**

### Question 1
>What is the **shape** of `r`?
><ol type='A'>
    <li><code>(5, 3, 2)</code></li>
    <li><code>(3, 2, 5)</code></li>
    <li><code>(2, 3, 5)</code></li>
</ol>

In [ ]:
# YOUR ANSWER: B
print(r.shape)

(3, 2, 5)


### Question 2
>What is the **dimension** of `r`?
><ol type='A'>
    <li>3</li>
    <li>5</li>
    <li>2</li>
</ol>



In [ ]:
# YOUR ANSWER: A
print(r.ndim)

3


### Question 3
>How many elements does `r` have?
><ol type='A'>
    <li>15</li>
    <li>20</li>
    <li>30</li>
</ol>


In [ ]:
# YOUR ANSWER: C
print(r.size)

30


## Indexing

In [ ]:
e = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
# Get the number 7 in array e using indexing
# Expected result: 7

# YOUR CODE HERE
print(e[1, 2])

7


In [ ]:
# Get the the first row of array e
# Expecte result: [1 2 3 4]

# YOUR CODE HERE
print(e[0])

[1 2 3 4]


### Question 1
>Given a 2D array `arr`, which of the following expressions returns the first column of `arr`?
><ol type='A'>
    <li><code>np.col(arr)[0]</code></li>
    <li><code>arr[:,0]</code></li>
    <li><code>arr[:][0]</code></li>
    <li><code>arr[0,:]</code></li>
</ol>

In [ ]:
# YOUR ANSWER: B
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr[:, 0])

[0 3]


### Question 2
>Given a 2D array `arr`, which of the following expressions returns the first and last columns of `arr`?
><ol type='A'>
    <li><code>np.columns(arr)[0,-1]</code></li>
    <li><code>arr[:,[0,1]]</code></li>
    <li><code>arr[:,-1]</code></li>
    <li><code>arr[:,[0,-1]]</code></li>
</ol>

In [ ]:
# YOUR ANSWER: D
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr[:, [0, -1]])

[[0 2]
 [3 5]]


### Question 3
>Given a 2D array called `arr`, which of the following expressions returns the reverse of `arr`?
><ol type='A'>
    <li><code>arr[::-1, ::-1]</code></li>
    <li><code>arr[:-1, :-1]</code></li>
    <li><code>arr[0:-1:1, 0:-1:1]</code></li>
    <li><code>arr[0::-1,0::-1]</code></li>
</ol>

*Example:*
```python
>>> arr = np.array([[1, 2, 3],
                    [4, 5, 6]])
>>> print(___) # Which expression gives the output below?
[[6 5 4]
 [3 2 1]]
```

In [ ]:
# YOUR ANSWER: A
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0:-1:1, 0:-1:1])

[[1 2]]



## Reshape array

In [ ]:
# Reshape 2x3 maxtrix b to an 1x6 row vector
# Expected result: [[1 2 3 4 5 6]]
d = np.array([[1, 2, 3], [4, 5, 6]])

# YOUR CODE HERE
print(d.reshape(1, 6))

[[1 2 3 4 5 6]]


In [ ]:
# Reshape this 1x6 matrix to an 6x1 matrix (in math they are called row vector and column vector)
d = np.array([[1, 2, 3, 4, 5, 6]])
# Expected result: [[1]
#                   [2]
#                   [3]
#                   [4]
#                   [5]
#                   [6]]

# YOUR CODE HERE
print(d.reshape(6, 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Question 1
>Write an ***expression*** which uses `.reshape(...)` to create a 3x3 matrix with the values ranging from 10 to 18.
```python
>>>> print(___.reshape(___)) # Your expression
[[10 11 12]
 [13 14 15]
 [16 17 18]]
```

In [ ]:
# YOUR CODE HERE
print(np.arange(10, 19).reshape(3, 3))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


### Question 2
>Given an array `arr` of any shape, which of the following expressions returns a flattened version of `arr`? Select all that apply.
><ol type='A'>
    <li><code>arr.reshape(1,-1)</code></li>
    <li><code>arr.flatten()</code></li>
    <li><code>arr.reshape(-1)</code></li>
    <li><code>np.flatten(arr)</code></li>
    <li><code>arr.reshape(-1,1)</code></li>
</ol>

*Example:*
```python
>>> arr = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
>>> print(___) # Which expressions give the output below?
[1 2 3 4 5 6]
```

**NOTE:** the result is a 1D array, not a 2D array with one row.

In [ ]:
# ANSWER: B and C
# YOUR CODE HERE
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.flatten())
print(arr.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


## Optional

### Boolean indexing

In [ ]:
b = np.concatenate([np.arange(1, 8), np.arange(6, 0, -1)], axis=0)
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# Get all the numbers that are more than 5.
# Expected: array([6, 7, 6])
# Your code here
print(b[b > 5])

[6 7 6]


In [ ]:
# Get all the numbers that are more than 2 but less than 6.
# Expected: array([3, 4, 5, 5, 4, 3])
# Your code here
print(b[(b > 2) & (b < 6)])

[3 4 5 5 4 3]


#### Question 1
>Write an ***expression*** that gives the same array as `b` EXCEPT all numbers greater than 5 is changed to 5 and other numbers stay the same. *(Hint: `np.where`)*

*Example:*
```python
>>> b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
>>> print(___) # Your expression
[1 2 3 4 5 5 5 5 5 4 3 2 1]
```

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
print(np.where(b > 5, 5, b))  # Your expression

[1 2 3 4 5 5 5 5 5 4 3 2 1]


#### Question 2
>Given an array `c` below, write an ***expression*** that gives an array of the *indices* of all non-zero numbers in `c`.

*Example:*
```python
>>> c = np.array([0, 10, 11, 0, 0, 12, 0, 13, 14])
>>> print(___) # Your expression
[1 2 5 7 8]
```

In [ ]:
c = np.array([0, 10, 11, 0, 0, 12, 0, 13, 14])

# Your code here
print(np.where(c != 0)[0])

[1 2 5 7 8]


### Aggregate functions

In [ ]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(s)

# Maximum number for the whole matrix
arr_max = s.max()  # fill in the blank
print("Max:", arr_max, sep="\n")

# Minimum number for the whole matrix
arr_min = s.min()
print("Min:", arr_min, sep="\n")

# Max element in each column
col_max = s.max(axis=0)
print("Max in each column:", col_max, sep="\n")

# Min element in each row
row_min = s.min(axis=1)
print("Min in each row:", row_min, sep="\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:
9
Min:
1
Max in each column:
[7 8 9]
Min in each row:
[1 4 7]


#### Question 1
>Given an array `arr` of any shape, which of the following expressions returns the mean of `arr`, assuming there's no error?
><ol type='A'>
    <li><code>np.mean(arr)</code></li>
    <li><code>arr.mean()</code></li>
    <li><code>arr.sum() / arr.size</code></li>
    <li>All of the above</li>
</ol>

In [ ]:
# ANSWER: D

# Example 1
print("Example 1:")
arr = np.arange(9).reshape(3, 3)
print(arr)
print("Mean of arr:", arr.mean())
print("Mean of arr:", np.mean(arr))
print("Mean of arr:", arr.sum() / arr.size)

print("\n", "-" * 30, "\n")
# Example 2
print("Example 2:")
arr = np.random.random((2, 5))
print(arr)
print("Mean of arr:", arr.mean())
print("Mean of arr:", np.mean(arr))
print("Mean of arr:", arr.sum() / arr.size)

Example 1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean of arr: 4.0
Mean of arr: 4.0
Mean of arr: 4.0

 ------------------------------ 

Example 2:
[[0.25896552 0.69035138 0.75682184 0.27727553 0.92754424]
 [0.97529609 0.95615668 0.63094342 0.16325321 0.7692742 ]]
Mean of arr: 0.640588208145928
Mean of arr: 0.640588208145928
Mean of arr: 0.640588208145928
